apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plannify-web-admin-app
  name: plannify-web-admin-app
  namespace: plannify-dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: plannify-dev-web-admin-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: plannify-web-admin-app
    spec:
      containers:
        - image: ghcr.io/plannify-truck-driver/web-admin-app:0.0.1-dev.100
          name: plannify-web-admin-app
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "92m"
              memory: "256Mi"
            limits:
              cpu: "128m"
              memory: "512Mi"
          ports:
            - containerPort: 4173
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 4173
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4173
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 4173
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
