apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plannify-dev-driver-api
  name: plannify-dev-driver-api
  namespace: plannify-dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: plannify-dev-driver-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: plannify-dev-driver-api
    spec:
      containers:
        - name: plannify-dev-driver-api
          image: ghcr.io/plannify-truck-driver/driver-api:0.0.10
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "16m"
              memory: "24Mi"
          ports:
            - containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: RUST_LOG
              value: DEBUG
            - name: ENVIRONMENT
              value: development
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-driver-api
                  key: JWT_SECRET_KEY
            - name: JWT_ACCESS_TTL
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-driver-api
                  key: JWT_ACCESS_TTL
            - name: JWT_REFRESH_TTL
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-driver-api
                  key: JWT_REFRESH_TTL
            - name: API_PORT
              value: "3000"
            - name: HEALTH_PORT
              value: "3001"
            - name: CORS_ORIGINS
              value: "0.0.0.0/0"
            - name: EMAIL_DOMAIN_DENYLIST
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-driver-api
                  key: EMAIL_DOMAIN_DENYLIST
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
