apiVersion: v1
kind: Service
metadata:
  name: plannify-pdf-service
  namespace: plannify-dev
spec:
  type: ClusterIP
  selector:
    app: plannify-pdf-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grpc
