apiVersion: v1
kind: Service
metadata:
  name: plannify-web-admin-app
  namespace: plannify-dev
spec:
  type: ClusterIP
  selector:
    app: plannify-web-admin-app
  ports:
    - port: 80
      targetPort: 4173
      protocol: TCP
      name: http
