apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plannify-image
  namespace: plannify
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: logo.plannify.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plannify-image
                port:
                  number: 80
  tls:
    - hosts:
        - logo.plannify.be
      secretName: plannify-image-tls
