apiVersion: v1
kind: Service
metadata:
  name: plannify-image
  namespace: plannify
spec:
  selector:
    app: plannify-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
