apiVersion: v1
kind: Service
metadata:
  name: plannify-dev-driver-api
  namespace: plannify-dev
spec:
  type: ClusterIP
  selector:
    app: plannify-dev-driver-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
