apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plannify-dev-admin-api
  name: plannify-dev-admin-api
  namespace: plannify-dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: plannify-dev-admin-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: plannify-dev-admin-api
    spec:
      containers:
        - image: ghcr.io/plannify-truck-driver/admin-api:0.0.1-dev.102
          name: plannify-dev-admin-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
          ports:
            - containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /admin/health
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /admin/health
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /admin/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: RUST_LOG
              value: DEBUG
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: JWT_SECRET
            - name: ACCESS_TOKEN_DURATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: ACCESS_TOKEN_DURATION_MINUTES
            - name: REFRESH_TOKEN_DURATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: REFRESH_TOKEN_DURATION_MINUTES
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dev-database-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: dev-database-secrets
                  key: REDIS_URL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
